name: BCREGISTRY ACCOUNT UI CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"

defaults:
  run:
    shell: bash

env:
  APP_NAME: "bcregistry-account"
  TAG_NAME: "dev"

jobs:
  bcregistry-account-cd-by-push:
    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'pwei1018/bcregistry-account-ui'
    environment:
      name: "dev"

    steps:
      - uses: actions/checkout@v2

      - name: Configure 1Password Connect

        uses: addnab/docker-run-action@v3
        with:
            image: 1password/op:2
            options: --rm -v ${{ github.workspace }}:/var/www -e OP_CONNECT_HOST=${{ secrets.OP_CONNECT_URL }} -e OP_CONNECT_TOKEN=${{ secrets.OP_CONNECT_TOKEN }} -e APP_ENV=${{ env.TAG_NAME }}
            run: |
              cd /var/www
              touch aaa.txt
              ls -l
              op inject -i ./devops/vaults.env -o .env
              cat .env

  bcregistry-account-cd-by-dispatch:
    runs-on: ubuntu-20.04

    if: github.event_name == 'workflow_dispatch' && github.repository == 'pwei1018/bcregistry-account-ui'
    environment:
      name: "${{ github.event.inputs.environment }}"

    steps:
      - uses: actions/checkout@v2
      - name: Set env by input
        run: |
          echo "TAG_NAME=${{ github.event.inputs.environment }}" >> $GITHUB_ENV

      - name: pull 1password image
        uses: docker://1password/op:2

      - name: Configure 1Password Connect
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_URL }}
          OP_CONNECT_TOKEN : ${{ secrets.OP_CONNECT_TOKEN }}
        run: |
          op read op://API/${{ env.TAG_NAME }}/registries-search-api/REGISTRIES_SEARCH_API_KEY